apiVersion: v1
kind: Service
metadata:
    name: imgproc-client
spec:
    type: LoadBalancer
    ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    selector:
      app: imgproc-client
      tier: frontend
